version: '3.7'

services:
  web:
    build: 
        context: ./bestdockerappever
        dockerfile: paravoz.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bestdockerappever/:/usr/src/bestdockerappever/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  postgres_data: